<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="ZXing.Net.Bindings.ImageSharp.V3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MayaPro.WarehouseApi.SharedKernel\MayaPro.WarehouseApi.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\NotoSans-Regular.ttf" />
    <EmbeddedResource Include="Resources\Fonts\NotoSans-Bold.ttf" />
  </ItemGroup>

</Project>
